version: '3.8'

services:
  djs-bot:
    container_name: djs-bot
    build:
      context: ../djs-bot
    restart: "unless-stopped"
    init: true
    env_file:
      ../djs-bot/.env
    stdin_open: true
    tty: true

  # dashboard:
  #   container_name: dashboard
  #   image: node:latest
  #   restart: "unless-stopped"
  #   init: true
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ../dashboard:/dashboard
  #   ports:
  #     - "3000:3000"
  #   working_dir: /dashboard
  #   command: ["npm", "run", "build-and-start"]

  postgres-db:
    image: postgres:15.2-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD:  root
      POSTGRES_USER:      root
      POSTGRES_DB:        base
      PGPORT:             5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  lavalink:
    image: fredboat/lavalink:3.7.12
    container_name: lavalink
    restart: unless-stopped
    hostname: docker.lavalink
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
      - ./lavalink/plugins/:/opt/Lavalink/plugins
    ports:
      - 2333:2333

volumes:
  postgres_data:
